import { Component, OnInit } from '@angular/core';
import {Service} from '../service';
import {DataSource} from '@angular/cdk/collections';

@Component({
  selector: 'app-admin',
  templateUrl: './admin.component.html',
  styleUrls: ['./admin.component.scss']
})
export class AdminComponent implements OnInit {

    services: Service[] = [];


  constructor() {


      this.services.push(new Service('Befriending', ['Scottish Borders', 'Edinburgh', 'Midlothian'], '0-1000', 'any', ['mix deal-with-stress-better edinburgh face-to-face-support feel-less-anxious feel-less-depressed feel-more-at-home-in-my-local-community feel-more-confident-and-better-about-myself feel-more-connected-and-get-out-and-about feel-safe find-out-what\'s-going-on-where-i-live get-well-and-stay-well have-more-friendships-in-my-life-and-get-to-know-more-people improve-the-relationships-i-have-with-others know-about-more-things-to-do-to-find-meaning-and-purpose-in-my-life make-changes-in-my-life midlothian rediscover-who-i-am scottish-borders spend-time-with-people-who-have-experienced-the-same-things support-from-someone-with-similar-experiences support-in-person']));
      this.services.push(new Service('Community Navigator', ['South West Edinburgh', 'South East Edinburgh'], '65-1000', 'any', ['mix deal-with-stress-better edinburgh feel-better-able-to-cope-with-life-and-my-feelings feel-more-connected-and-get-out-and-about find-out-what\'s-going-on-where-i-live get-well-and-stay-well information know-about-more-things-to-do-to-find-meaning-and-purpose-in-my-life know-what-support,-tools-and-guides-are-available-that-will-help-me-manage-better support-in-person']));
      this.services.push(new Service('Men\'s SHARE', ['Midlothian'], '25-50', 'male', ['mix be-able-to-cope-with-the-affects-of-childhood-trauma deal-with-stress-better feel-better-able-to-cope-with-life-and-my-feelings feel-less-anxious feel-less-depressed feel-more-at-home-in-my-local-community feel-more-confident-and-better-about-myself feel-more-connected-and-get-out-and-about feel-safe get-well-and-stay-well have-more-friendships-in-my-life-and-get-to-know-more-people improve-the-relationships-i-have-with-others know-about-more-things-to-do-to-find-meaning-and-purpose-in-my-life know-what-support,-tools-and-guides-are-available-that-will-help-me-manage-better make-changes-in-my-life midlothian rediscover-who-i-am spend-time-thinking-about-what-is-important-to-me spend-time-with-people-who-have-experienced-the-same-things support-in-person support-with-others-(group) talk-to-someone-who-will-listen orange-bg']));
      this.services.push(new Service('Art Psychotherapy', ['Midlothian'], '0-1000', 'any', ['mix deal-with-stress-better midlothian']));
      this.services.push(new Service('ROWAN, Respect Our Woodland and Nature', ['Midlothian'], '0-1000', 'any', ['mix deal-with-stress-better feel-better-able-to-cope-with-life-and-my-feelings feel-less-anxious feel-less-depressed feel-more-at-home-in-my-local-community feel-more-confident-and-better-about-myself feel-more-connected-and-get-out-and-about feel-safe get-well-and-stay-well have-more-friendships-in-my-life-and-get-to-know-more-people improve-the-relationships-i-have-with-others know-about-more-things-to-do-to-find-meaning-and-purpose-in-my-life make-changes-in-my-life midlothian rediscover-who-i-am spend-time-thinking-about-what-is-important-to-me support-with-others-(group)']));
      this.services.push(new Service('South West Edinburgh', ['South West Edinburgh'], '0-1000', 'any', ['mix edinburgh']));
      this.services.push(new Service('Support from Home', ['Midlothian'], '0-1000', 'any', ['mix deal-with-stress-better feel-better-able-to-cope-with-life-and-my-feelings feel-less-anxious feel-less-depressed feel-more-at-home-in-my-local-community feel-more-confident-and-better-about-myself feel-more-connected-and-get-out-and-about feel-safe find-out-what\'s-going-on-where-i-live get-well-and-stay-well have-more-friendships-in-my-life-and-get-to-know-more-people know-what-support,-tools-and-guides-are-available-that-will-help-me-manage-better make-changes-in-my-life midlothian rediscover-who-i-am support-in-person talk-to-someone-who-will-listen']));
      this.services.push(new Service('Equal Access, supporting people from minority and ethnic communities', ['East Lothian', 'Edinburgh', 'Midlothian'], '16-1000', 'any', ['mix deal-with-stress-better east-lothian edinburgh face-to-face-support feel-less-anxious feel-less-depressed feel-more-at-home-in-my-local-community feel-more-confident-and-better-about-myself feel-more-connected-and-get-out-and-about feel-safe find-out-what\'s-going-on-where-i-live get-well-and-stay-well have-more-friendships-in-my-life-and-get-to-know-more-people improve-the-relationships-i-have-with-others know-about-more-things-to-do-to-find-meaning-and-purpose-in-my-life make-changes-in-my-life midlothian rediscover-who-i-am spend-time-with-people-who-have-experienced-the-same-things support-from-someone-with-similar-experiences support-with-others-(group)']));
      this.services.push(new Service('CLEAR, Community Lived Experience for Alcohol and Drugs Recovery', ['Midlothian'], '18-1000', 'any', ['mix deal-with-stress-better feel-better-able-to-cope-with-life-and-my-feelings feel-less-anxious feel-less-depressed feel-more-confident-and-better-about-myself feel-more-connected-and-get-out-and-about feel-safe get-well-and-stay-well have-more-friendships-in-my-life-and-get-to-know-more-people improve-the-relationships-i-have-with-others know-about-more-things-to-do-to-find-meaning-and-purpose-in-my-life know-what-support,-tools-and-guides-are-available-that-will-help-me-manage-better make-changes-in-my-life midlothian rediscover-who-i-am spend-time-thinking-about-what-is-important-to-me spend-time-with-people-who-have-experienced-the-same-things support-from-someone-with-similar-experiences support-in-person support-with-others-(group) talk-to-someone-who-will-listen']));
      this.services.push(new Service('Guided Self-Help', ['Edinburgh', 'Midlothian'], '0-1000', 'any', ['mix deal-with-stress-better edinburgh feel-better-able-to-cope-with-life-and-my-feelings feel-less-anxious feel-less-depressed feel-more-confident-and-better-about-myself feel-safe get-well-and-stay-well improve-the-relationships-i-have-with-others know-what-support,-tools-and-guides-are-available-that-will-help-me-manage-better make-changes-in-my-life midlothian support-in-person talk-to-someone-who-will-listen']));
      this.services.push(new Service('South Queensferry Developments', ['South Queensferry'], '0-1000', 'any', ['mix edinburgh']));
      this.services.push(new Service('Counselling', [''], '0-1000', 'any', ['mix be-able-to-cope-with-the-affects-of-childhood-trauma deal-with-stress-better edinburgh feel-better-able-to-cope-with-life-and-my-feelings feel-less-anxious feel-less-depressed feel-more-confident-and-better-about-myself feel-safe get-well-and-stay-well improve-the-relationships-i-have-with-others make-changes-in-my-life rediscover-who-i-am spend-time-thinking-about-what-is-important-to-me support-in-person talk-to-someone-who-will-listen']));
      this.services.push(new Service('Trauma Support Services', [''], '16-1000', 'any', ['mix be-able-to-cope-with-the-affects-of-childhood-trauma deal-with-stress-better edinburgh feel-better-able-to-cope-with-life-and-my-feelings feel-less-anxious feel-less-depressed feel-more-at-home-in-my-local-community feel-more-confident-and-better-about-myself feel-more-connected-and-get-out-and-about feel-safe find-out-what\'s-going-on-where-i-live get-well-and-stay-well have-more-friendships-in-my-life-and-get-to-know-more-people improve-the-relationships-i-have-with-others know-about-more-things-to-do-to-find-meaning-and-purpose-in-my-life know-what-support,-tools-and-guides-are-available-that-will-help-me-manage-better make-changes-in-my-life rediscover-who-i-am spend-time-with-people-who-have-experienced-the-same-things support-in-person talk-to-someone-who-will-listen']));
      this.services.push(new Service('Trauma Counselling Line Scotland', [''], '16-1000', 'any', ['mix be-able-to-cope-with-the-affects-of-childhood-trauma deal-with-stress-better feel-better-able-to-cope-with-life-and-my-feelings feel-less-anxious feel-less-depressed feel-more-at-home-in-my-local-community feel-more-confident-and-better-about-myself feel-more-connected-and-get-out-and-about feel-safe get-well-and-stay-well have-more-friendships-in-my-life-and-get-to-know-more-people improve-the-relationships-i-have-with-others know-about-more-things-to-do-to-find-meaning-and-purpose-in-my-life make-changes-in-my-life other-areas rediscover-who-i-am spend-time-thinking-about-what-is-important-to-me support-on-the-phone talk-to-someone-who-will-listen']));
      this.services.push(new Service('Information Websites', ['East Lothian', 'Edinburgh', 'Midlothian', 'West Lothian'], '0-1000', 'any', ['mix deal-with-stress-better drop-in east-lothian edinburgh feel-better-able-to-cope-with-life-and-my-feelings feel-more-connected-and-get-out-and-about get-well-and-stay-well ind-out-what\'s-going-on-where-i-live information know-about-more-things-to-do-to-find-meaning-and-purpose-in-my-life know-what-support,-tools-and-guides-are-available-that-will-help-me-manage-better midlothian support-in-person support-on-the-phone west-lothian']));
      this.services.push(new Service('Day Service', ['Midlothian'], '0-1000', 'any', ['mix deal-with-stress-better feel-better-able-to-cope-with-life-and-my-feelings feel-less-anxious feel-less-depressed feel-more-at-home-in-my-local-community feel-more-confident-and-better-about-myself feel-more-connected-and-get-out-and-about feel-safe find-out-what\'s-going-on-where-i-live get-well-and-stay-well have-more-friendships-in-my-life-and-get-to-know-more-people improve-the-relationships-i-have-with-others know-about-more-things-to-do-to-find-meaning-and-purpose-in-my-life know-what-support,-tools-and-guides-are-available-that-will-help-me-manage-better make-changes-in-my-life midlothian spend-time-with-people-who-have-experienced-the-same-things support-with-others-(group) talk-to-someone-who-will-listen']));
      this.services.push(new Service('Early Intervention and Crisis Response Service', ['Midlothian'], '0-1000', 'any', ['mix feel-less-anxious feel-less-depressed feel-safe midlothian support-in-person support-on-the-phone talk-to-someone-who-will-listen']));
      this.services.push(new Service('Out of Hours Service', ['Midlothian'], '0-1000', 'any', ['mix midlothian']));
      this.services.push(new Service('Wellbeing Access Point', ['Midlothian'], '18-65', 'any', ['mix deal-with-stress-better drop-in feel-better-able-to-cope-with-life-and-my-feelings feel-less-anxious feel-less-depressed feel-more-connected-and-get-out-and-about find-out-what\'s-going-on-where-i-live get-well-and-stay-well information know-about-more-things-to-do-to-find-meaning-and-purpose-in-my-life know-what-support,-tools-and-guides-are-available-that-will-help-me-manage-better make-changes-in-my-life midlothian spend-time-thinking-about-what-is-important-to-me support-in-person talk-to-someone-who-will-listen']));
      this.services.push(new Service('Anxiety and Depression Support Groups', ['East Lothian', 'Edinburgh', 'Midlothian', 'West Lothian'], '16-1000', 'any', ['mix east-lothian edinburgh feel-less-depressed feel-more-connected-and-get-out-and-about midlothian support-with-others-(group) west-lothian']));
      this.services.push(new Service('Wellbeing Gateway', ['South West Edinburgh'], '18-64', 'any', ['mix deal-with-stress-better edinburgh face-to-face-support feel-better-able-to-cope-with-life-and-my-feelings feel-less-anxious feel-less-depressed feel-more-at-home-in-my-local-community feel-more-confident-and-better-about-myself feel-more-connected-and-get-out-and-about feel-safe find-out-what\'s-going-on-where-i-live get-well-and-stay-well have-more-friendships-in-my-life-and-get-to-know-more-people improve-the-relationships-i-have-with-others information know-about-more-things-to-do-to-find-meaning-and-purpose-in-my-life know-what-support,-tools-and-guides-are-available-that-will-help-me-manage-better make-changes-in-my-life rediscover-who-i-am spend-time-thinking-about-what-is-important-to-me spend-time-with-people-who-have-experienced-the-same-things support-from-someone-with-similar-experiences support-in-person']));
      this.services.push(new Service('Community Mental Health and Wellbeing Service', ['West Lothian'], '55-1000', 'any', ['mix deal-with-stress-better feel-more-at-home-in-my-local-community feel-more-connected-and-get-out-and-about find-out-what\'s-going-on-where-i-live get-well-and-stay-well information know-about-more-things-to-do-to-find-meaning-and-purpose-in-my-life know-what-support,-tools-and-guides-are-available-that-will-help-me-manage-better make-changes-in-my-life support-in-person talk-to-someone-who-will-listen west-lothian']));
      this.services.push(new Service('Wellbeing College', ['Scottish Borders'], '16-1000', 'any', ['mix scottish-borders']));
      this.services.push(new Service('The Listening Space', ['South East Edinburgh'], '0-1000', 'any', ['mix edinburgh']));
      this.services.push(new Service('My Assets and Personal Strengths (MAPS)', ['Edinburgh'], '0-1000', 'any', ['mix edinburgh']));
      this.services.push(new Service('Peer Collaborative', ['Edinburgh'], '0-1000', 'any', ['mix edinburgh']));
      this.services.push(new Service('Oasis', ['South East Edinburgh'], '18-1000', 'female', ['mix']));

  }

  ngOnInit(); {
  }

}
